spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  service-sid: ${TWILIO_WALLAS_SERVICE_SID}

wallas:
  phone-number: ${WALLAS_PHONE_NUMBER}
  pin-code: ${WALLAS_PIN_CODE}

features:
  sms-provider: ${FEATURES_SMS_PROVIDER}

app-center:
  api-token: ${APP_CENTER_API_TOKEN}
  base-url: https://api.appcenter.ms/v0.1/apps
  owner-name: havard.falk
  ios-app-name: wallas-2
  android-app-name: wallas-1

