spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-247-125-116.eu-west-1.compute.amazonaws.com:5432/d8htirls7roqs2?sslmode=require
    # Get credentials from heroku
    username:
    password:
