spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}

twillio:
  account-sid: ${TWILLIO_ACCOUNT_SID}
  auth-token: ${TWILLIO_AUTH_TOKEN}
  phone-number: ${TWILLIO_PHONE_NUMBER}

wallas:
  phone-number: ${WALLAS_PHONE_NUMBER}
  pin-code: ${WALLAS_PIN_CODE}
