spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}

twillio:
  account-sid: ${TWILLIO_ACCOUNT_SID}
  auth-token: ${TWILLIO_AUTH_TOKEN}
  phone-number: ${TWILLIO_PHONE_NUMBER}

wallas:
  phone-number: ${WALLAS_PHONE_NUMBER}
  pin-code: ${WALLAS_PIN_CODE}

features:
  sms-enabled: ${FEATURES_SMS_ENABLED}

app-center:
  api-token: ${APP_CENTER_API_TOKEN}
  base-url: https://api.appcenter.ms/v0.1/apps
  owner-name: havard.falk
  ios-app-name: wallas-2
  android-app-name: wallas-1

